export const ClientActionTypes = {
    SET_CURRENT_CLIENT: "SET_CURRENT_CLIENT",
    FETCH_CLIENT_START: "FETCH_CLIENT_START",
    FETCH_CLIENT_SUCCESS: "FETCH_CLIENT_SUCCESS",
    FETCH_CLIENT_FAILURE: "FETCH_CLIENT_FAILURE"
}